# @package _global_
run_name: debug

data:
  batch_size: 4
  num_workers: 0

trainer:
  max_steps: 100
  val_every_n_steps: 100
  log_every_n_steps: 1
  limit_val_batches: 1
  limit_test_batches: 1
  enable_checkpointing: false
